server:
  port: 8012

spring:
  datasource:
    username: root
    password: carry0610A!
    url: jdbc:mysql://123.56.73.147:3306/baba_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.example.springboot_son.entity

#  redis:
#    host: 192.168.3.46
#    port: 6379
#    max-active: 100
#    max-wait: 30000
#    max-idle: 20
#    min-idle: 0
#    timeout: 5000ms

#showSql
logging:
  level:
    com:
      example:
        mapper : debug