server:
  port: 8012
#  ssl:
#    key-store: classpath:zyj.pfx
#    key-store-password: 8Q64w0Uo
#    key-store-type: pfx 8Q64w0Uo
#  ssl:   #SSL证书路径 一定要加上classpath:
#   key-store:classpath: zyj.jks
#   #SSL证书密码
#    key-store-password: 8Q64w0Uo
#   #证书类型  grant all on *.* to 'zyj'@'%'IDENTIFIED BY 'zyj0610A!';
#   key-store-type: JKS
#    #证书别名
#   key-alias: alias
spring:
#  datasource:
#    username: root
#    password: carry0610A!
#    url: jdbc:mysql://123.56.73.147:3306/baba_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver

    datasource:
      username: zyj
      password: 85DpKzWczm4BZziS
      url: jdbc:mysql://39.102.56.91:3306/baba_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver

# pagehelper grant all on *.* to 'zyj'@'%'IDENTIFIED BY 'zyj0610A!';
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


mybatis:
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.example.springboot_son.entity

  redis:
    host: 39.102.56.91
    port: 6379
    max-active: 100
    max-wait: 30000
    max-idle: 20
    min-idle: 0
    timeout: 5000ms

##生产环境
#  redis:
#    host:  123.56.73.147
#    port: 6379
#    password: 0524A
#    max-active: 100
#    max-wait: 30000
#    max-idle: 20
#    min-idle: 0
#    timeout: 5000ms
#  redis:
#    database: 0
#    host: localhost
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#    password:  # 0524A # zyj0610A
#    port: 6379
# nohup java -jar springboot_son-0.0.1-SNAPSHOT.jar &  执行
# ps aux|grep springboot_son-0.0.1-SNAPSHOT.jar 查看进程
#showSql
logging:
  level:
    com:
      example:
        mapper : debug