server:
  port: 8012
#  ssl:
#    key-store: classpath:zyj.pfx
#    key-store-password: 8Q64w0Uo
#    key-store-type: pfx 8Q64w0Uo   可以求
#  ssl:   #SSL证书路径 一定要加上classpath:
#   key-store:classpath: zyj.jks
#   #SSL证书密码
#    key-store-password: 8Q64w0Uo
#   #证书类型
#   key-store-type: JKS
#    #证书别名
#   key-alias: alias
spring:
  datasource:
    username: root
    password: carry0610A!
    url: jdbc:mysql://123.56.73.147:3306/baba_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.example.springboot_son.entity

#  redis:
#    host: 192.168.3.46
#    port: 6379
#    max-active: 100
#    max-wait: 30000
#    max-idle: 20
#    min-idle: 0
#    timeout: 5000ms


#  redis:
#    host: localhost
#    port: 6379
#    password: 0524A
#    max-active: 100
#    max-wait: 30000
#    max-idle: 20
#    min-idle: 0
#    timeout: 5000ms
  redis:
    database: 0
    host: 123.56.73.147
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: 0524A
    port: 6379

#showSql
logging:
  level:
    com:
      example:
        mapper : debug